-- MySQL Script generated by MySQL Workbench
-- Thứ bảy, 02 Tháng 10 Năm 2021 08:50:58 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema F11_N12_PRO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema F11_N12_PRO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `F11_N12_PRO` ;
USE `F11_N12_PRO` ;

-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`api` (
  `id` VARCHAR(36) NOT NULL,
  `url` VARCHAR(70) NOT NULL,
  `method` VARCHAR(35) NULL DEFAULT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `userName` VARCHAR(36) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `email` VARCHAR(36) NULL DEFAULT NULL,
  `phone` VARCHAR(36) NULL DEFAULT NULL,
  `address` VARCHAR(36) NULL DEFAULT NULL,
  `isActive` INT NULL DEFAULT NULL,
  `identityNumber` VARCHAR(36) NULL DEFAULT NULL,
  `socialInsurance` VARCHAR(36) NULL DEFAULT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`employee` (
  `id` VARCHAR(36) NOT NULL,
  `lastName` VARCHAR(70) NOT NULL,
  `fullName` INT NULL DEFAULT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC),
  CONSTRAINT `employee_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `F11_N12_PRO`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`form` (
  `id` VARCHAR(36) NOT NULL,
  `receiver` VARCHAR(70) NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `dueDate` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `userId` (`userId` ASC),
  CONSTRAINT `form_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `F11_N12_PRO`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`role_permission` (
  `id` VARCHAR(36) NOT NULL,
  `roleId` INT NOT NULL,
  `apiId` VARCHAR(36) NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_permission_roleId_roleId_unique` (`roleId` ASC),
  UNIQUE INDEX `role_permission_apiId_apiId_unique` (`apiId` ASC),
  CONSTRAINT `role_permission_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `F11_N12_PRO`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `role_permission_ibfk_2`
    FOREIGN KEY (`apiId`)
    REFERENCES `F11_N12_PRO`.`api` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`user_Authorize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`user_Authorize` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `roleId` INT NOT NULL,
  `isDeleted` TINYINT(1) NOT NULL DEFAULT '0',
  `createdBy` VARCHAR(255) NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `managerId` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_Authorize_userId_roleId_unique` (`userId` ASC, `roleId` ASC),
  INDEX `roleId` (`roleId` ASC),
  CONSTRAINT `user_Authorize_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `F11_N12_PRO`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_Authorize_ibfk_2`
    FOREIGN KEY (`roleId`)
    REFERENCES `F11_N12_PRO`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `F11_N12_PRO`.`formDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`formDetail` (
  `id` VARCHAR(36) NOT NULL,
  `formId` VARCHAR(45) NULL,
  `content` VARCHAR(255) NULL,
  `managerComment` VARCHAR(200) NULL,
  `evaluatedValue` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formDetail_1_idx` (`formId` ASC),
  CONSTRAINT `fk_formDetail_1`
    FOREIGN KEY (`formId`)
    REFERENCES `F11_N12_PRO`.`form` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `F11_N12_PRO` ;

-- -----------------------------------------------------
-- Placeholder table for view `F11_N12_PRO`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `F11_N12_PRO`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `F11_N12_PRO`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `F11_N12_PRO`.`view1`;
USE `F11_N12_PRO`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
